set timeout 360
set prompt "(>|#) $"
log_file -noappend "~/nxosv-console.explog"

spawn telnet 127.0.0.1 52099

# wait for system to become ready 
expect "System ready"
send "\r"

# log in with the admin user
expect "login:"
send "admin\r"
expect "Password:"
send "Cisco1984!\r"

# create the vagrant user
expect -re $prompt {
	send "configure\r"
	send "feature bash-shell\r"
	send "username vagrant password vagrant role network-admin\r"
	send "username vagrant sshkey ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ==\r"
}

# enable network automation features
expect -re $prompt {
	send "feature nxapi\r"
	send "feature scp-server\r"
}

# disable timeout for the virtual terminal line 
expect -re $prompt {
	send "line vty\r"
	send "exec-timeout 0\r"
	send "exit\r"
}

# configure the management interface
expect -re $prompt {
	send "interface mgmt0\r"
	send "ip address dhcp\r"
	send "no shut\r"
	send "end\r"
}

# save the running configuration to local nvram
expect -re $prompt {
	send "copy running-config startup-config\r"
	send "\r"
}

# allow adequate time for configuration save to complete
sleep 30
send "\r"
expect -re $prompt

# log out
send "exit\r"
