set timeout 360
set prompt "(>|#) $"
set nxos "10.6.2.F"
set is_lite 1
log_file -noappend "~/nxosv-console.explog"

spawn telnet 127.0.0.1 52099

# abort power on auto provisioning (poap)
expect "Abort Power On Auto Provisioning"
send "yes\r"

# allow adequate time for system to become ready
sleep 90

# disable secure password standard
expect "Do you want to enforce secure password standard"
send "no\r"

# set admin user password
sleep 3
expect "Enter the password for"
send "Cisco1984\r"

# confirm the admin user password
sleep 3
expect "Confirm the password for"
send "Cisco1984\r"

# disable setup mode
expect "Would you like to enter the basic configuration dialog"
send "no\r"

# log in with the admin user
expect "login:"
send "admin\r"
expect "Password:"
send "Cisco1984\r"

# configure the boot image and reload
expect -re $prompt {
	send "configure\r"
	send "username admin password Cisco1984\r"
}
send "no feature signature-verification\r"
expect "Are you sure you want to continue"
send "y\r"
expect -re $prompt {
    if {$is_lite} {
        send "boot nxos bootflash:nxos64-cs-lite.$nxos.bin\r"
    } else {
        send "boot nxos bootflash:nxos64-cs.$nxos.bin\r"
    }
	send "end\r"
}

# save the running configuration to local nvram
send "copy running-config startup-config\r"
expect -re $prompt

# allow adequate time for configuration save to complete
sleep 30
send "\r"
expect -re $prompt

# log out
send "exit\r"
